apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: PRACTICA_REGISTRY/kafka:PRACTICA_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_ADVERTISED_HOST
          value: "kafka"
        readinessProbe:
          exec:
            command:
            - /opt/kafka/bin/kafka-topics.sh
            - --bootstrap-server
            - localhost:29092
            - --list
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 25
          failureThreshold: 18
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
